#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Sep  5 12:45:52 2019

@author: mcmcgraw
"""

import cdsapi

c = cdsapi.Client()

c.retrieve(
    'reanalysis-era5-single-levels',
    {
        'product_type':'reanalysis',
        'format':'netcdf',
        'variable':'2m_temperature',
        'year':'2019',
        'month':'01',
        'day':[
            '01','02','03',
            '04','05','06'
        ],
        'time':'00:00'
    },
    'download.nc')
