#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Aug 12 14:18:14 2019

@author: mcmcgraw
"""
#clear workspace each time we run
def clear_all():
    """Clears all the variables from the workspace of the spyder application."""
    gl = globals().copy()
    for var in gl:
        if var[0] == '_': continue
        if 'func' in str(globals()[var]): continue
        if 'module' in str(globals()[var]): continue

        del globals()[var]
if __name__ == "__main__":
    clear_all()
    
import netCDF4
from netCDF4 import Dataset, num2date, MFDataset
import numpy as np
import numpy.ma as ma
import datetime
from datetime import datetime, timedelta, date
import xarray as xr
import glob

    
#Basic info about time
model_name = 'ecmwf'
model_type = 'cf'
var = 'Z500'
filepath_load = '/home/disk/sipn/rclancy/{model_name}/{model_type}/native/{var}/'.format(model_name=model_name,
                  model_type=model_type,var=var)
file1 = Dataset('/home/disk/sipn/rclancy/{model_name}/{model_type}/native/{var}/ecmwf_1999-02-04.netcdf'.format(model_name=model_name,
                  model_type=model_type,var=var))
file2 = Dataset('/home/disk/sipn/rclancy/{model_name}/{model_type}/native/{var}/ecmwf_2016-02-04.netcdf'.format(model_name=model_name,
                  model_type=model_type,var=var))
gh = file1.variables['gh'][:]
gh2 = file2.variables['gh'][:]
lat = file1.variables['latitude'][:]
lon = file1.variables['longitude'][:]
time = file1.variables['time'][:]
time2 = file2.variables['time'][:]
time = ma.getdata(time)
time2 = ma.getdata(time2)
calendar = file1.variables['time'].calendar
time_units = file1.variables['time'].units
time_value = num2date(time,units=time_units,calendar=calendar)
#Loop through.  Skip all initialization dates for 07-04

years = np.arange(1999,2019,1)
months = np.arange(1,12)
str_time = [i.strftime("%Y-%m-%d %H:%M") for i in time_value] 
#list of filenames
fnames = sorted(glob.glob('/home/disk/sipn/rclancy/ecmwf/cf/native/Z500/*.netcdf'))
fnames_short = fnames[0:300]
Z500_all = np.array([])
TIME_all = np.array([])

#for ifile in np.arange(0,len(fnames_short)):
ifile = 200
fname = fnames_short[ifile]
f_list = list(fnames_short[ifile])
#check month (f_list[57])
#if(f_list[57] == '7') and (f_list[60] == '4'):
#    #continue
#    print('damn')
#else:
#    f_ds = Dataset(fname)
#    z_ifile = f_ds.variables['gh'][:]
#    z_ifile = ma.getdata(z_ifile)
#    time_ifile = f_ds.variables['time'][:]
#    time_ima = ma.getdata(time_ifile)
#    itime_units = f_ds.variables['time'].units
#    itime_calendar = f_ds.variables['time'].calendar
#    time_val = num2date(time_ima,units=itime_units,calendar=itime_calendar)
#    str_time_i = [itime.strftime("%Y-%m-%f %H:%M") for itime in time_val]
#    if ifile == 0:
#        Z500_all = z_ifile
#        TIME_all = str_time_i
#    else:
#        Z500_all = np.vstack((Z500_all,z_ifile))
#        TIME_all = np.hstack((TIME_all,str_time_i))
        
        
        